PRAGMA defer_foreign_keys = true;
-- PGNest Data Migration Script
-- Generated for Cloudflare D1 database
-- Organization: org-demo-pgwalo

PRAGMA defer_foreign_keys = true;

INSERT OR REPLACE INTO organizations (id, name, owner_user_id, account_state, subscription_plan, created_at)
  VALUES ('org-demo-pgwalo', 'Blue Haven Operations', 'user-owner', 'Trial / Pending Setup', 'Trial', '2026-09-17T11:38:05.721Z');

INSERT OR REPLACE INTO properties (id, organization_id, status, name, tagline, gender, city, locality, address, lat, lng, cover_image, gallery_images, starting_price, rating, review_count, rooms, amenities, rules, notice_period_days, gate_closing_time, food_included, verified, featured, contact_phone, contact_email, owner_name, default_rent_due_day, total_floors, modules) VALUES ('prop-1', 'org-demo-pgwalo', 'Active', 'Blue Haven Luxury Living PG', 'Modern, high-tech co-living space with organic home-cooked meals', 'Boys', 'Bengaluru', 'HSR Layout, Sector 3', 'Plot 412, 14th Main Rd, Sector 3, HSR Layout, Bengaluru, Karnataka 560102', 12.9116, 77.6446, 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1000&q=80', '["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1000&q=80","https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1000&q=80","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80","https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1000&q=80"]', 8500, 4.8, 64, '[{"id":"r1-single","type":"Single","rentPerMonth":14500,"deposit":20000,"availableBeds":1,"totalBeds":8,"hasAttachedBath":true,"hasAC":true,"hasBalcony":true},{"id":"r1-double","type":"Double","rentPerMonth":9500,"deposit":15000,"availableBeds":3,"totalBeds":16,"hasAttachedBath":true,"hasAC":true,"hasBalcony":false},{"id":"r1-triple","type":"Triple","rentPerMonth":8500,"deposit":12000,"availableBeds":2,"totalBeds":12,"hasAttachedBath":true,"hasAC":false,"hasBalcony":false}]', '["wifi","ac","food","laundry","attached_bath","power_backup","cctv","gym","ro_water","housekeeping"]', '["Gate closes at 11:30 PM (biometric re-entry with log)","Visitors allowed in lounge until 8:00 PM","No smoking or alcohol on premises","Quiet hours observed between 11:00 PM and 7:00 AM"]', 30, '11:30 PM', 1, 1, 1, '+91 98450 12345', 'stay@bluehavenpg.com', 'Rajesh Sharma', 7, NULL, '{"foodManagement":true,"attendance":true,"visitorManagement":true,"onlinePayments":true,"chat":true}');
INSERT OR REPLACE INTO properties (id, organization_id, status, name, tagline, gender, city, locality, address, lat, lng, cover_image, gallery_images, starting_price, rating, review_count, rooms, amenities, rules, notice_period_days, gate_closing_time, food_included, verified, featured, contact_phone, contact_email, owner_name, default_rent_due_day, total_floors, modules) VALUES ('prop-2', 'org-demo-pgwalo', 'Active', 'Serene Heights Premium PG for Women', 'Safe, gated biometric campus with round-the-clock female warden', 'Girls', 'Bengaluru', 'Koramangala, 5th Block', 'Near Sony World Signal, 5th Block Koramangala, Bengaluru, Karnataka 560095', 12.9352, 77.6245, 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=80', '["https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=80","https://images.unsplash.com/photo-1540518614846-7ede433c4ef2?auto=format&fit=crop&w=1000&q=80","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80"]', 9000, 4.9, 92, '[{"id":"r2-single","type":"Single","rentPerMonth":16000,"deposit":22000,"availableBeds":2,"totalBeds":6,"hasAttachedBath":true,"hasAC":true,"hasBalcony":true},{"id":"r2-double","type":"Double","rentPerMonth":11000,"deposit":16000,"availableBeds":4,"totalBeds":18,"hasAttachedBath":true,"hasAC":true,"hasBalcony":true},{"id":"r2-triple","type":"Triple","rentPerMonth":9000,"deposit":14000,"availableBeds":3,"totalBeds":12,"hasAttachedBath":true,"hasAC":false,"hasBalcony":false}]', '["wifi","ac","food","laundry","attached_bath","power_backup","cctv","gym","ro_water","housekeeping","geyser"]', '["Biometric access 24/7 with female security officer","Parents permitted in visiting room","Meal timings strictly observed: Breakfast 7:30-10:00, Dinner 8:00-10:30","Notice period 30 days mandatory"]', 30, '10:30 PM', 1, 1, 1, '+91 98860 99881', 'care@sereneheights.com', 'Sunita Mehra', 7, NULL, '{"foodManagement":true,"attendance":true,"visitorManagement":true,"onlinePayments":true,"chat":true}');
INSERT OR REPLACE INTO properties (id, organization_id, status, name, tagline, gender, city, locality, address, lat, lng, cover_image, gallery_images, starting_price, rating, review_count, rooms, amenities, rules, notice_period_days, gate_closing_time, food_included, verified, featured, contact_phone, contact_email, owner_name, default_rent_due_day, total_floors, modules) VALUES ('prop-3', 'org-demo-pgwalo', 'Active', 'CyberNest Unisex Smart Co-Living', 'Modern tech-worker hub near Hinjewadi Phase 1 with coworking lounge', 'Unisex', 'Pune', 'Hinjewadi Phase 1', 'Survey 48, Behind Rajiv Gandhi Infotech Park, Hinjewadi, Pune 411057', 18.5913, 73.7389, 'https://images.unsplash.com/photo-1502005229762-ee1b2da97e06?auto=format&fit=crop&w=1000&q=80', '["https://images.unsplash.com/photo-1502005229762-ee1b2da97e06?auto=format&fit=crop&w=1000&q=80","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80"]', 7800, 4.7, 48, '[{"id":"r3-single","type":"Single","rentPerMonth":13500,"deposit":18000,"availableBeds":2,"totalBeds":10,"hasAttachedBath":true,"hasAC":true,"hasBalcony":true},{"id":"r3-double","type":"Double","rentPerMonth":9000,"deposit":13000,"availableBeds":5,"totalBeds":20,"hasAttachedBath":true,"hasAC":true,"hasBalcony":false},{"id":"r3-triple","type":"Triple","rentPerMonth":7800,"deposit":10000,"availableBeds":4,"totalBeds":15,"hasAttachedBath":false,"hasAC":false,"hasBalcony":false}]', '["wifi","ac","food","laundry","attached_bath","power_backup","cctv","gym","parking"]', '["Dedicated co-working desks open 24/7","ID verification required for all non-resident guests","Zero disturbance during remote working hours"]', 20, '24 Hours Open', 1, 1, 0, '+91 97654 32109', 'info@cybernestpg.com', 'Vikram Patel', 7, NULL, '{"foodManagement":true,"attendance":true,"visitorManagement":true,"onlinePayments":true,"chat":true}');
INSERT OR REPLACE INTO properties (id, organization_id, status, name, tagline, gender, city, locality, address, lat, lng, cover_image, gallery_images, starting_price, rating, review_count, rooms, amenities, rules, notice_period_days, gate_closing_time, food_included, verified, featured, contact_phone, contact_email, owner_name, default_rent_due_day, total_floors, modules) VALUES ('prop-4', 'org-demo-pgwalo', 'Active', 'Gachibowli Silicon Stay PG', 'Premium fully-furnished AC suites near DLF Cyber City & Amazon HQ', 'Boys', 'Hyderabad', 'Gachibowli, Telecom Nagar', 'Road No 4, Telecom Nagar Extension, Gachibowli, Hyderabad 500032', 17.4401, 78.3489, 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1000&q=80', '["https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1000&q=80","https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80"]', 8200, 4.6, 39, '[{"id":"r4-single","type":"Single","rentPerMonth":15000,"deposit":20000,"availableBeds":1,"totalBeds":5,"hasAttachedBath":true,"hasAC":true,"hasBalcony":true},{"id":"r4-double","type":"Double","rentPerMonth":9500,"deposit":14000,"availableBeds":3,"totalBeds":14,"hasAttachedBath":true,"hasAC":true,"hasBalcony":false},{"id":"r4-triple","type":"Triple","rentPerMonth":8200,"deposit":11000,"availableBeds":2,"totalBeds":9,"hasAttachedBath":true,"hasAC":false,"hasBalcony":false}]', '["wifi","ac","food","laundry","attached_bath","power_backup","cctv","parking","housekeeping"]', '["Vegetarian and Non-Vegetarian South/North Indian food separate prep","Gate closes at midnight 12:00 AM","Security deposit refundable on 30-day exit notice"]', 30, '12:00 AM', 1, 1, 0, '+91 94401 55667', 'manager@siliconstay.in', 'Kishore Reddy', 7, NULL, '{"foodManagement":true,"attendance":true,"visitorManagement":true,"onlinePayments":true,"chat":true}');

INSERT OR REPLACE INTO residents (id, organization_id, status, name, email, phone, avatar, property_id, property_name, room_number, room_type, bed_number, monthly_rent, deposit_amount, move_in_date, rent_status, rent_due_date, last_payment_date, emergency_contact, kyc_verified, notes, deposit_state, agreement_state, previous_dues, advance_balance, outstanding_balance, notice_period_days) VALUES ('res-1', 'org-demo-pgwalo', 'Active', 'Ananya Sen', 'ananya.sen@example.com', '+91 98765 43210', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80', 'prop-1', 'Blue Haven Luxury Living PG', '204', 'Double', 'Bed B', 9500, 15000, '2025-08-15', 'Pending', '2026-09-07', '2026-08-05', '+91 98300 11223 (Father)', 1, 'Software Engineer at Infosys', 'Held', 'Pending', 0, 0, 9500, 30);
INSERT OR REPLACE INTO residents (id, organization_id, status, name, email, phone, avatar, property_id, property_name, room_number, room_type, bed_number, monthly_rent, deposit_amount, move_in_date, rent_status, rent_due_date, last_payment_date, emergency_contact, kyc_verified, notes, deposit_state, agreement_state, previous_dues, advance_balance, outstanding_balance, notice_period_days) VALUES ('res-2', 'org-demo-pgwalo', 'Active', 'Rohan Deshmukh', 'rohan.d@example.com', '+91 98111 22334', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80', 'prop-1', 'Blue Haven Luxury Living PG', '101', 'Single', 'Bed A', 14500, 20000, '2025-06-01', 'Paid', '2026-09-05', '2026-09-01', '+91 98222 33445 (Brother)', 1, 'Product Designer at Swiggy', 'Held', 'Pending', 0, 0, 0, 30);
INSERT OR REPLACE INTO residents (id, organization_id, status, name, email, phone, avatar, property_id, property_name, room_number, room_type, bed_number, monthly_rent, deposit_amount, move_in_date, rent_status, rent_due_date, last_payment_date, emergency_contact, kyc_verified, notes, deposit_state, agreement_state, previous_dues, advance_balance, outstanding_balance, notice_period_days) VALUES ('res-3', 'org-demo-pgwalo', 'Active', 'Tanmay Bhattacharya', 'tanmay.b@example.com', '+91 97333 44556', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80', 'prop-1', 'Blue Haven Luxury Living PG', '204', 'Double', 'Bed A', 9500, 15000, '2025-09-10', 'Paid', '2026-09-05', '2026-09-02', '+91 98311 55667 (Mother)', 1, 'Data Analyst at Flipkart', 'Held', 'Pending', 0, 0, 0, 30);
INSERT OR REPLACE INTO residents (id, organization_id, status, name, email, phone, avatar, property_id, property_name, room_number, room_type, bed_number, monthly_rent, deposit_amount, move_in_date, rent_status, rent_due_date, last_payment_date, emergency_contact, kyc_verified, notes, deposit_state, agreement_state, previous_dues, advance_balance, outstanding_balance, notice_period_days) VALUES ('res-4', 'org-demo-pgwalo', 'Active', 'Karthik Raja', 'karthik.r@example.com', '+91 94444 88990', 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80', 'prop-1', 'Blue Haven Luxury Living PG', '302', 'Triple', 'Bed C', 8500, 12000, '2026-01-10', 'Overdue', '2026-09-01', '2026-07-31', '+91 94433 22110 (Uncle)', 0, 'Awaiting college graduation verification', 'Held', 'Pending', 0, 0, 8500, 30);

INSERT OR REPLACE INTO booking_requests (id, organization_id, resident_status, reserved_bed_id, reservation_expiry, token_amount, applicant_name, email, phone, property_id, property_name, room_type, preferred_move_in_date, occupancy_type, status, request_date, message, type, visit_date, visit_time_slot, reference_id, allocated_room_number, allocated_bed_number) VALUES ('req-1', 'org-demo-pgwalo', NULL, NULL, NULL, NULL, 'Vikrant Chaudhary', 'vikrant.c@example.com', '+91 98990 12345', 'prop-1', 'Blue Haven Luxury Living PG', 'Double', '2026-09-15', 'Working Professional', 'Pending', '2026-09-03', 'Joining Wipro HSR campus. Need food included and quiet desk space.', 'booking', NULL, NULL, 'req-1', NULL, NULL);
INSERT OR REPLACE INTO booking_requests (id, organization_id, resident_status, reserved_bed_id, reservation_expiry, token_amount, applicant_name, email, phone, property_id, property_name, room_type, preferred_move_in_date, occupancy_type, status, request_date, message, type, visit_date, visit_time_slot, reference_id, allocated_room_number, allocated_bed_number) VALUES ('req-2', 'org-demo-pgwalo', NULL, NULL, NULL, NULL, 'Deepak Nair', 'deepak.n@example.com', '+91 98470 56789', 'prop-1', 'Blue Haven Luxury Living PG', 'Single', '2026-09-20', 'Working Professional', 'Pending', '2026-09-04', 'Looking for single occupancy room with attached bathroom.', 'booking', NULL, NULL, 'req-2', NULL, NULL);

INSERT OR REPLACE INTO attendance_records (id, person_id, person_name, person_type, room_number, date, timestamp, type, status, notes) VALUES ('att-1', 'res-1', 'Ananya Sen', 'Resident', '204', '2026-09-05', '08:45 AM', 'Check-Out', 'On-Time', 'Heading to office');
INSERT OR REPLACE INTO attendance_records (id, person_id, person_name, person_type, room_number, date, timestamp, type, status) VALUES ('att-2', 'res-2', 'Rohan Deshmukh', 'Resident', '101', '2026-09-05', '09:15 AM', 'Check-Out', 'On-Time');
INSERT OR REPLACE INTO attendance_records (id, person_id, person_name, person_type, role, date, timestamp, type, status, notes) VALUES ('att-3', 'staff-1', 'Sunil Kumar', 'Staff', 'Supervisor', '2026-09-05', '06:30 AM', 'Check-In', 'On-Time', 'Morning shift opening');
INSERT OR REPLACE INTO attendance_records (id, person_id, person_name, person_type, room_number, date, timestamp, type, status, notes) VALUES ('att-4', 'res-3', 'Tanmay Bhattacharya', 'Resident', '204', '2026-09-04', '10:45 PM', 'Check-In', 'Late', 'Late client meeting approval');

INSERT OR REPLACE INTO staff_members (id, name, role, phone, avatar, property_id, shift, today_status, last_clock_in) VALUES ('staff-1', 'Sunil Kumar', 'Manager', '+91 98711 54321', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80', 'prop-1', 'Morning (6 AM - 2 PM)', 'Checked-In', '06:30 AM');
INSERT OR REPLACE INTO staff_members (id, name, role, phone, avatar, property_id, shift, today_status, last_clock_in) VALUES ('staff-2', 'Ramesh Yadav', 'Mess Cook', '+91 97188 23456', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=200&q=80', 'prop-1', 'Morning (6 AM - 2 PM)', 'Checked-In', '05:45 AM');
INSERT OR REPLACE INTO staff_members (id, name, role, phone, avatar, property_id, shift, today_status, last_clock_in) VALUES ('staff-3', 'Manoj Singh', 'Housekeeping', '+91 98100 87654', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80', 'prop-1', 'Morning (6 AM - 2 PM)', 'Checked-In', '07:00 AM');
INSERT OR REPLACE INTO staff_members (id, name, role, phone, avatar, property_id, shift, today_status, last_clock_in) VALUES ('staff-4', 'Bhawani Shankar', 'Security Guard', '+91 99555 12121', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80', 'prop-1', 'Night (10 PM - 6 AM)', 'Checked-Out', 'Yesterday 10:00 PM');

INSERT OR REPLACE INTO staff_tasks (id, title, description, category, assigned_to_name, time_slot, priority, completed) VALUES ('task-1', 'Daily Deep Cleaning 2nd Floor Corridor', 'Mop floor with disinfectant, clean shoe racks and dust window sills.', 'Cleaning', 'Manoj Singh', '09:00 AM - 10:30 AM', 'High', 1);
INSERT OR REPLACE INTO staff_tasks (id, title, description, category, assigned_to_name, time_slot, priority, completed) VALUES ('task-2', 'Inspect RO Purifier TDS & Water Level', 'Check TDS reading on 1st & 3rd floor water dispensers and log values.', 'Maintenance', 'Sunil Kumar', '11:00 AM - 11:30 AM', 'Medium', 0);
INSERT OR REPLACE INTO staff_tasks (id, title, description, category, assigned_to_name, time_slot, priority, completed) VALUES ('task-3', 'Lunch Preparation & Dining Hall Setup', 'Dal Tadka, Paneer Butter Masala, Jeera Rice, Phulkas, Fresh Salad.', 'Kitchen', 'Ramesh Yadav', '11:30 AM - 01:30 PM', 'High', 0);
INSERT OR REPLACE INTO staff_tasks (id, title, description, category, assigned_to_name, time_slot, priority, completed) VALUES ('task-4', 'Biometric Access Scanner Audit', 'Sync attendance cloud backup and clean scanner optical lens.', 'Security', 'Sunil Kumar', '04:00 PM - 05:00 PM', 'Low', 0);

INSERT OR REPLACE INTO broadcast_notifications (id, title, message, category, target, timestamp, sender) VALUES ('b-1', 'Monthly Rent Reminder (September 2026)', 'Dear residents, kindly clear your room rent by the 7th of September to avoid late clearance charges. Instant UPI receipts available in your portal.', 'Rent', 'All Residents', '2026-09-02 10:00 AM', 'Property Owner (Rajesh Sharma)');
INSERT OR REPLACE INTO broadcast_notifications (id, title, message, category, target, timestamp, sender) VALUES ('b-2', 'Overhead Water Tank Cleaning Notice', 'Water supply will be temporarily paused between 2:00 PM and 4:00 PM this coming Saturday for scheduled quarterly tank sanitization.', 'Maintenance', 'All Residents', '2026-09-04 03:30 PM', 'Supervisor Sunil');
INSERT OR REPLACE INTO broadcast_notifications (id, title, message, category, target, timestamp, sender) VALUES ('b-3', 'Sunday Special Dinner: Dum Biryani & Gulab Jamun', 'This Sunday dinner features Hyderabadi Veg/Paneer Dum Biryani, Chicken Dum Biryani, Mirchi ka Salan, and hot Gulab Jamun!', 'Food', 'All Residents', '2026-09-04 07:00 PM', 'Mess Chef Ramesh');

INSERT OR REPLACE INTO meal_plans (day, breakfast, lunch, snacks, dinner, special_note) VALUES ('Monday', 'Masala Idli & Crispy Vada with Coconut Chutney, Sambar, Tea/Coffee', 'Steamed Rice, Yellow Dal Tadka, Aloo Gobhi, Phulkas, Curd & Salad', 'Adrak Chai with Onion Pakodas / Biscuits', 'Paneer Butter Masala, Roti, Mixed Veg Pulav, Boondi Raita', 'Pure ghee tadka');
INSERT OR REPLACE INTO meal_plans (day, breakfast, lunch, snacks, dinner) VALUES ('Tuesday', 'Aloo Paratha with Fresh Curd, Pickle, Mint Chutney, Milk/Tea', 'Rajma Masala, Steamed Basmati Rice, Bhindi Do Pyaza, Chapati, Papad', 'Filter Coffee with Poha / Chivda', 'Egg Curry / Mushroom Masala, Tawa Roti, Jeera Rice, Dal Fry');
INSERT OR REPLACE INTO meal_plans (day, breakfast, lunch, snacks, dinner, special_note) VALUES ('Wednesday', 'Mysore Masala Dosa, Potato Palya, Tomato & Coconut Chutney', 'Kadhi Pakoda, Kichdi / Steamed Rice, Baingan Bharta, Salad', 'Masala Chai with Samosas', 'Chicken Curry / Shahi Paneer, Garlic Naan / Tawa Roti, Veg Biryani', 'Non-veg & Veg options available');
INSERT OR REPLACE INTO meal_plans (day, breakfast, lunch, snacks, dinner) VALUES ('Thursday', 'Poha with Roasted Peanuts, Sev, Lemon & Boiled Eggs / Sprouts', 'Chole Masala, Bhature / Chapati, Jeera Rice, Cucumber Raita', 'Green Tea / Regular Tea with Veg Cutlets', 'Mix Veg Korma, Chapati, Dal Makhani, Steamed Rice');
INSERT OR REPLACE INTO meal_plans (day, breakfast, lunch, snacks, dinner) VALUES ('Friday', 'Uttapam with Sambar, Chana Dal Chutney, Fresh Fruits', 'Dal Palak, Aloo Shimla Mirch, Phulkas, Steamed Rice, Rasam', 'Hot Bournvita / Chai with Banana Cake', 'Matar Paneer, Tawa Roti, Veg Pulao, Gulab Jamun');
INSERT OR REPLACE INTO meal_plans (day, breakfast, lunch, snacks, dinner) VALUES ('Saturday', 'Poori with Spiced Aloo Sabzi, Halwa, Tea/Coffee', 'South Indian Thali: Rice, Sambar, Rasam, Poriyal, Curd, Appalam', 'Chai with Murukku & Mixture', 'Chinese Night: Veg Fried Rice, Hakka Noodles, Manchurian Gravy');
INSERT OR REPLACE INTO meal_plans (day, breakfast, lunch, snacks, dinner, special_note) VALUES ('Sunday', 'Chole Kulche / Bread Omelette, Seasonal Juice, Tea', 'Hyderabadi Dum Biryani (Chicken & Paneer), Mirchi Ka Salan, Raita', 'Sweet Lassi & Roasted Makhana', 'Light Khichdi, Tomato Soup, Papad, Roasted Paneer Tikka', 'Grand Weekend Feast!');

INSERT OR REPLACE INTO chat_messages (id, sender_role, sender_name, recipient_name, text, timestamp, is_owner) VALUES ('msg-1', 'owner', 'Rajesh Sharma (Owner)', 'Ananya Sen', 'Hello Ananya! Welcome to Blue Haven PG. Hope your room 204 is comfortable.', 'Yesterday 10:15 AM', 1);
INSERT OR REPLACE INTO chat_messages (id, sender_role, sender_name, recipient_name, text, timestamp, is_owner) VALUES ('msg-2', 'resident', 'Ananya Sen', 'Rajesh Sharma', 'Hi Rajesh ji, thanks a lot! Everything is great, just wanted to check if the 2nd floor WiFi router can be restarted as ping was fluctuating slightly.', 'Yesterday 11:30 AM', 0);
INSERT OR REPLACE INTO chat_messages (id, sender_role, sender_name, recipient_name, text, timestamp, is_owner) VALUES ('msg-3', 'owner', 'Rajesh Sharma (Owner)', 'Ananya Sen', 'Certainly! I have asked Sunil to reboot the dual-band mesh repeater. It should be 300 Mbps rock solid now.', 'Yesterday 11:45 AM', 1);
INSERT OR REPLACE INTO chat_messages (id, sender_role, sender_name, recipient_name, text, timestamp, is_owner) VALUES ('msg-4', 'resident', 'Ananya Sen', 'Rajesh Sharma', 'Working super smooth now! Also, I will be clearing this month rent today evening via UPI.', 'Today 09:30 AM', 0);

INSERT OR REPLACE INTO maintenance_tickets (id, title, category, room_number, resident_name, description, priority, status, created_at) VALUES ('tkt-1', 'AC Remote Battery Depleted', 'Electrical', '204', 'Ananya Sen', 'The split AC remote is not turning on. Needs new AAA batteries or replacement.', 'Normal', 'In-Progress', '2026-09-04');
INSERT OR REPLACE INTO maintenance_tickets (id, title, category, room_number, resident_name, description, priority, status, created_at) VALUES ('tkt-2', 'Bathroom Tap Slow Drip', 'Plumbing', '101', 'Rohan Deshmukh', 'Washbasin faucet has a minor continuous drip.', 'Normal', 'Resolved', '2026-09-02');

-- No data for users

INSERT OR REPLACE INTO beds (id, bed_number, room_id, room_number, property_id, floor, building, sharing_type, status, current_tenant_id, current_tenant_name, monthly_rent, deposit, organization_id) VALUES ('bed-101-A', '101-A', NULL, '101', 'prop-1', 1, 'Tower A', 'Single', 'Occupied', 'res-2', 'Rohan Deshmukh', 14500, 20000, 'org-demo-pgwalo');
INSERT OR REPLACE INTO beds (id, bed_number, room_id, room_number, property_id, floor, building, sharing_type, status, monthly_rent, deposit, organization_id, current_tenant_id, reserved_for_resident_id) VALUES ('bed-102-A', '102-A', NULL, '102', 'prop-1', 1, 'Tower A', 'Single', 'Available', 14500, 20000, 'org-demo-pgwalo', NULL, NULL);
INSERT OR REPLACE INTO beds (id, bed_number, room_id, room_number, property_id, floor, building, sharing_type, status, current_tenant_id, current_tenant_name, monthly_rent, deposit, organization_id) VALUES ('bed-201-A', '201-A', NULL, '201', 'prop-1', 2, 'Tower A', 'Double', 'Occupied', 'res-3', 'Priya Iyer', 9500, 15000, 'org-demo-pgwalo');
INSERT OR REPLACE INTO beds (id, bed_number, room_id, room_number, property_id, floor, building, sharing_type, status, monthly_rent, deposit, organization_id, current_tenant_id, reserved_for_resident_id) VALUES ('bed-201-B', '201-B', NULL, '201', 'prop-1', 2, 'Tower A', 'Double', 'Booking Pending', 9500, 15000, 'org-demo-pgwalo', NULL, NULL);
INSERT OR REPLACE INTO beds (id, bed_number, room_id, room_number, property_id, floor, building, sharing_type, status, current_tenant_id, current_tenant_name, monthly_rent, deposit, organization_id) VALUES ('bed-204-A', '204-A', NULL, '204', 'prop-1', 2, 'Tower A', 'Single', 'Occupied', 'res-1', 'Ananya Sen', 13500, 20000, 'org-demo-pgwalo');
INSERT OR REPLACE INTO beds (id, bed_number, room_id, room_number, property_id, floor, building, sharing_type, status, current_tenant_id, current_tenant_name, monthly_rent, deposit, organization_id) VALUES ('bed-301-A', '301-A', NULL, '301', 'prop-1', 3, 'Tower A', 'Triple', 'Occupied', 'res-4', 'Karthik Raja', 8500, 12000, 'org-demo-pgwalo');
INSERT OR REPLACE INTO beds (id, bed_number, room_id, room_number, property_id, floor, building, sharing_type, status, monthly_rent, deposit, next_available_date, organization_id, current_tenant_id, reserved_for_resident_id) VALUES ('bed-301-B', '301-B', NULL, '301', 'prop-1', 3, 'Tower A', 'Triple', 'Cleaning', 8500, 12000, '2026-09-08', 'org-demo-pgwalo', NULL, NULL);
INSERT OR REPLACE INTO beds (id, bed_number, room_id, room_number, property_id, floor, building, sharing_type, status, monthly_rent, deposit, organization_id, current_tenant_id, reserved_for_resident_id) VALUES ('bed-301-C', '301-C', NULL, '301', 'prop-1', 3, 'Tower A', 'Triple', 'Available', 8500, 12000, 'org-demo-pgwalo', NULL, NULL);
INSERT OR REPLACE INTO beds (id, bed_number, room_id, room_number, property_id, floor, building, sharing_type, status, current_tenant_id, current_tenant_name, monthly_rent, deposit, next_available_date, organization_id, reserved_for_resident_id) VALUES ('bed-302-A', '302-A', NULL, '302', 'prop-1', 3, 'Tower A', 'Double', 'Notice Period', NULL, 'Aditya Varma', 9500, 15000, '2026-09-30', 'org-demo-pgwalo', NULL);
INSERT OR REPLACE INTO beds (id, bed_number, room_id, room_number, property_id, floor, building, sharing_type, status, monthly_rent, deposit, organization_id, current_tenant_id, reserved_for_resident_id) VALUES ('bed-302-B', '302-B', NULL, '302', 'prop-1', 3, 'Tower A', 'Double', 'Ready', 9500, 15000, 'org-demo-pgwalo', NULL, NULL);

INSERT OR REPLACE INTO leads (id, name, phone, email, property_id, property_name, room_type_preference, budget_max, preferred_move_in, stage, source, assigned_to, notes, created_at, last_follow_up, budget, expected_move_in_date) VALUES ('lead-1', 'Siddharth Roy', '+91 99887 76655', 'siddharth.roy@gmail.com', 'prop-1', 'Blue Haven Luxury Living PG', 'Single', 15000, '2026-09-15', 'Visit Scheduled', 'Google Search', 'Kavita Menon', 'Works at Oracle HSR. Wants quiet single room with high-speed WiFi for work-from-home.', '2026-09-01', '2026-09-04', 15000, '2026-09-15');
INSERT OR REPLACE INTO leads (id, name, phone, email, property_id, property_name, room_type_preference, budget_max, preferred_move_in, stage, source, assigned_to, notes, created_at, last_follow_up, budget, expected_move_in_date) VALUES ('lead-2', 'Megha Nair', '+91 98451 22334', 'megha.nair@outlook.com', 'prop-1', 'Blue Haven Luxury Living PG', 'Double', 10000, '2026-09-20', 'Interested', 'Walk-In / Referral', 'Devendra Patil', 'Visited yesterday, liked food quality and gym. Awaiting parents confirmation.', '2026-09-02', '2026-09-04', 10000, '2026-09-20');
INSERT OR REPLACE INTO leads (id, name, phone, email, property_id, property_name, room_type_preference, budget_max, preferred_move_in, stage, source, assigned_to, notes, created_at, last_follow_up, budget, expected_move_in_date) VALUES ('lead-3', 'Abhishek Kulkarni', '+91 97112 33445', 'abhi.kulkarni@gmail.com', 'prop-1', 'Blue Haven Luxury Living PG', 'Triple', 9000, '2026-10-01', 'Contacted', 'Website Form', 'Kavita Menon', 'College student at NIFT Bengaluru. Requested virtual tour link.', '2026-09-03', '2026-09-04', 9000, '2026-10-01');

INSERT OR REPLACE INTO electricity_meter_readings (id, property_id, property_name, room_number, meter_number, previous_reading, current_reading, units_consumed, rate_per_unit, fixed_charges, total_amount, reading_date, staff_name, meter_photo_url, status, is_anomaly) VALUES ('emr-1', 'prop-1', 'Blue Haven Luxury Living PG', '204', 'MTR-HSR-204', 1240, 1390, 150, 8.5, 75, 1350, '2026-09-01', 'Sunil Kumar', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=400&q=80', 'Verified', 0);
INSERT OR REPLACE INTO electricity_meter_readings (id, property_id, property_name, room_number, meter_number, previous_reading, current_reading, units_consumed, rate_per_unit, fixed_charges, total_amount, reading_date, staff_name, meter_photo_url, status, is_anomaly) VALUES ('emr-2', 'prop-1', 'Blue Haven Luxury Living PG', '101', 'MTR-HSR-101', 2100, 2280, 180, 8.5, 75, 1605, '2026-09-01', 'Devendra Patil', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=400&q=80', 'Verified', 0);
INSERT OR REPLACE INTO electricity_meter_readings (id, property_id, property_name, room_number, meter_number, previous_reading, current_reading, units_consumed, rate_per_unit, fixed_charges, total_amount, reading_date, staff_name, meter_photo_url, status, is_anomaly, anomaly_reason) VALUES ('emr-3', 'prop-1', 'Blue Haven Luxury Living PG', '301', 'MTR-HSR-301', 950, 1380, 430, 8.5, 75, 3730, '2026-09-01', 'Sunil Kumar', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=400&q=80', 'Flagged', 1, 'Sudden 180% surge compared to 3-month average of 150 units. Suspected continuous AC usage or wiring leak.');

-- skipped property_electricity_reconciliation (no D1 table)

INSERT OR REPLACE INTO security_deposit_records (id, resident_id, resident_name, room_number, property_id, deposit_received, received_date, status, deductions, total_deductions, final_refund_amount, notes) VALUES ('dep-1', 'res-1', 'Ananya Sen', '204', 'prop-1', 20000, '2026-02-01', 'Held', '[]', 0, 20000, 'Security deposit held in escrow account. Eligible for full refund upon 30-day notice.');
INSERT OR REPLACE INTO security_deposit_records (id, resident_id, resident_name, room_number, property_id, deposit_received, received_date, status, deductions, total_deductions, final_refund_amount, notes) VALUES ('dep-2', 'res-5', 'Aditya Varma', '302', 'prop-1', 15000, '2025-10-01', 'Settlement Pending', '[{"id":"ded-1","category":"Damage","amount":1200,"reason":"Broken study desk drawer sliding track","approvedByOwner":true},{"id":"ded-2","category":"Electricity","amount":850,"reason":"Final pro-rated electricity consumption for September","approvedByOwner":true}]', 2050, 12950, 'Tenant on notice period ending Sept 30. Move-out inspection signed.');

INSERT OR REPLACE INTO rent_agreements (id, agreement_number, resident_id, resident_name, parent_guardian_name, tenant_permanent_address, tenant_current_address, tenant_college_or_office, tenant_id_document_type, tenant_id_document_masked, property_id, property_name, property_address, owner_name, owner_phone, room_number, bed_number, monthly_rent, security_deposit, electricity_terms, notice_period_days, start_date, end_date, rules_summary, emergency_contact_name, emergency_contact_phone, status, owner_signed, tenant_signed, signed_date, tenant_dob) VALUES ('agr-1', 'PGN-BLR-2026-0089', 'res-1', 'Ananya Sen', 'Debabrata Sen', 'Flat 4B, Greenwood Apts, Salt Lake City, Kolkata, WB 700064', 'Room 204, Blue Haven PG, 14th Main Rd, HSR Sector 3, Bengaluru', 'Infosys Limited, Electronic City Phase 1, Bengaluru', 'Aadhaar', 'XXXX-XXXX-8492', 'prop-1', 'Blue Haven Luxury Living PG', 'Plot 412, 14th Main Rd, Sector 3, HSR Layout, Bengaluru, Karnataka 560102', 'Rajesh Sharma', '+91 98450 12345', '204', '204-A', 13500, 20000, 'Billed monthly per sub-meter @ ₹8.50/unit consumed.', 30, '2026-02-01', '2027-01-31', '["Gate curfew strictly at 11:00 PM unless prior digital approval obtained","No smoking or unauthorized alcohol consumption inside rooms or common areas","Overnight guests require warden approval 24 hours in advance","Quiet hours observed between 10:30 PM and 7:00 AM"]', 'Debabrata Sen (Father)', '+91 94330 11223', 'Active', 1, 1, '2026-02-02', '2001-05-14');

INSERT OR REPLACE INTO visitor_passes (id, resident_id, resident_name, room_number, visitor_name, visitor_phone, purpose, expected_arrival, check_in_time, check_out_time, status, approved_by) VALUES ('vis-1', 'res-1', 'Ananya Sen', '204', 'Ritu Sen (Sister)', '+91 98300 45678', 'Family visit & lunch', '2026-09-05 13:00', '2026-09-05 13:15', '2026-09-05 16:30', 'Checked-Out', 'Devendra Patil (Warden)');
INSERT OR REPLACE INTO visitor_passes (id, resident_id, resident_name, room_number, visitor_name, visitor_phone, purpose, expected_arrival, status, approved_by) VALUES ('vis-2', 'res-2', 'Rohan Deshmukh', '101', 'Aman Verma', '+91 99112 33445', 'College project discussion', '2026-09-05 18:00', 'Pre-Approved', 'Auto pre-approved by resident');

INSERT OR REPLACE INTO audit_logs (id, user_id, user_name, user_role, action, entity, timestamp, details) VALUES ('aud-1', 'user-owner', 'Rajesh Sharma', 'owner', 'Rent Status Updated', 'Resident: Ananya Sen', '2026-09-04 10:24', 'Marked August rent ₹13,500 as Paid via UPI transaction.');
INSERT OR REPLACE INTO audit_logs (id, user_id, user_name, user_role, action, entity, timestamp, details) VALUES ('aud-2', 'user-warden', 'Devendra Patil', 'warden', 'Electricity Meter Logged', 'Room 204 Meter', '2026-09-01 09:15', 'Logged reading 1390 units with verified photo proof.');
INSERT OR REPLACE INTO audit_logs (id, user_id, user_name, user_role, action, entity, timestamp, details) VALUES ('aud-3', 'user-owner', 'Rajesh Sharma', 'owner', 'New Staff Assigned', 'Bhawani Shankar (Security Guard)', '2026-08-28 14:00', 'Assigned to Night Shift (10 PM - 6 AM) at Tower A.');

INSERT OR REPLACE INTO system_settings (currency, rent_due_day, late_fee_grace_days, late_fee_amount, default_electricity_rate, electricity_billing_model, deposit_refund_notice_days, emergency_maintenance_sla_hours, high_maintenance_sla_hours, normal_maintenance_sla_hours, low_maintenance_sla_hours) VALUES ('INR (₹)', 5, 5, 250, 8.5, 'Room-Level', 30, 2, 6, 24, 48);

INSERT OR REPLACE INTO role_permissions (role, permissions) VALUES ('admin', '{"property":{"view":true,"create":true,"edit":true,"delete":true,"publish":true,"approve":true},"rooms":{"view":true,"create":true,"edit":true,"delete":true,"allocateBed":true},"tenants":{"view":true,"create":true,"edit":true,"move":true,"vacate":true,"viewDocs":true},"rent":{"view":true,"generate":true,"collect":true,"verify":true,"refund":true},"electricity":{"view":true,"enterReadings":true,"editReadings":true,"generateBills":true,"approveBills":true},"agreements":{"create":true,"view":true,"verify":true,"generate":true,"download":true},"maintenance":{"create":true,"assign":true,"update":true,"resolve":true},"reports":{"view":true,"export":true}}');
INSERT OR REPLACE INTO role_permissions (role, permissions) VALUES ('owner', '{"property":{"view":true,"create":true,"edit":true,"delete":false,"publish":true,"approve":false},"rooms":{"view":true,"create":true,"edit":true,"delete":true,"allocateBed":true},"tenants":{"view":true,"create":true,"edit":true,"move":true,"vacate":true,"viewDocs":true},"rent":{"view":true,"generate":true,"collect":true,"verify":true,"refund":true},"electricity":{"view":true,"enterReadings":true,"editReadings":true,"generateBills":true,"approveBills":true},"agreements":{"create":true,"view":true,"verify":true,"generate":true,"download":true},"maintenance":{"create":true,"assign":true,"update":true,"resolve":true},"reports":{"view":true,"export":true}}');
INSERT OR REPLACE INTO role_permissions (role, permissions) VALUES ('manager', '{"property":{"view":true,"create":false,"edit":true,"delete":false,"publish":false,"approve":false},"rooms":{"view":true,"create":true,"edit":true,"delete":false,"allocateBed":true},"tenants":{"view":true,"create":true,"edit":true,"move":true,"vacate":true,"viewDocs":true},"rent":{"view":true,"generate":true,"collect":true,"verify":true,"refund":false},"electricity":{"view":true,"enterReadings":true,"editReadings":true,"generateBills":true,"approveBills":false},"agreements":{"create":true,"view":true,"verify":true,"generate":true,"download":true},"maintenance":{"create":true,"assign":true,"update":true,"resolve":true},"reports":{"view":true,"export":true}}');
INSERT OR REPLACE INTO role_permissions (role, permissions) VALUES ('warden', '{"property":{"view":true,"create":false,"edit":false,"delete":false,"publish":false,"approve":false},"rooms":{"view":true,"create":false,"edit":false,"delete":false,"allocateBed":true},"tenants":{"view":true,"create":false,"edit":false,"move":false,"vacate":false,"viewDocs":false},"rent":{"view":true,"generate":false,"collect":false,"verify":false,"refund":false},"electricity":{"view":true,"enterReadings":true,"editReadings":false,"generateBills":false,"approveBills":false},"agreements":{"create":false,"view":true,"verify":false,"generate":false,"download":false},"maintenance":{"create":true,"assign":true,"update":true,"resolve":true},"reports":{"view":false,"export":false}}');
INSERT OR REPLACE INTO role_permissions (role, permissions) VALUES ('accountant', '{"property":{"view":true,"create":false,"edit":false,"delete":false,"publish":false,"approve":false},"rooms":{"view":true,"create":false,"edit":false,"delete":false,"allocateBed":false},"tenants":{"view":true,"create":false,"edit":false,"move":false,"vacate":false,"viewDocs":false},"rent":{"view":true,"generate":true,"collect":true,"verify":true,"refund":true},"electricity":{"view":true,"enterReadings":false,"editReadings":false,"generateBills":true,"approveBills":true},"agreements":{"create":false,"view":true,"verify":false,"generate":false,"download":true},"maintenance":{"view":true,"assign":false,"update":false,"resolve":false,"create":false},"reports":{"view":true,"export":true}}');
INSERT OR REPLACE INTO role_permissions (role, permissions) VALUES ('staff', '{"property":{"view":true,"create":false,"edit":false,"delete":false,"publish":false,"approve":false},"rooms":{"view":true,"create":false,"edit":false,"delete":false,"allocateBed":false},"tenants":{"view":false,"create":false,"edit":false,"move":false,"vacate":false,"viewDocs":false},"rent":{"view":false,"generate":false,"collect":false,"verify":false,"refund":false},"electricity":{"view":true,"enterReadings":true,"editReadings":false,"generateBills":false,"approveBills":false},"agreements":{"create":false,"view":false,"verify":false,"generate":false,"download":false},"maintenance":{"create":true,"assign":false,"update":true,"resolve":true},"reports":{"view":false,"export":false}}');
INSERT OR REPLACE INTO role_permissions (role, permissions) VALUES ('resident', '{"property":{"view":true,"create":false,"edit":false,"delete":false,"publish":false,"approve":false},"rooms":{"view":true,"create":false,"edit":false,"delete":false,"allocateBed":false},"tenants":{"view":false,"create":false,"edit":false,"move":false,"vacate":false,"viewDocs":false},"rent":{"view":true,"generate":false,"collect":false,"verify":false,"refund":false},"electricity":{"view":true,"enterReadings":false,"editReadings":false,"generateBills":false,"approveBills":false},"agreements":{"create":false,"view":true,"verify":false,"generate":false,"download":true},"maintenance":{"create":true,"assign":false,"update":false,"resolve":false},"reports":{"view":false,"export":false}}');
INSERT OR REPLACE INTO role_permissions (role, permissions) VALUES ('public', '{"property":{"view":true,"create":false,"edit":false,"delete":false,"publish":false,"approve":false},"rooms":{"view":true,"create":false,"edit":false,"delete":false,"allocateBed":false},"tenants":{"view":false,"create":false,"edit":false,"move":false,"vacate":false,"viewDocs":false},"rent":{"view":false,"generate":false,"collect":false,"verify":false,"refund":false},"electricity":{"view":false,"enterReadings":false,"editReadings":false,"generateBills":false,"approveBills":false},"agreements":{"create":false,"view":false,"verify":false,"generate":false,"download":false},"maintenance":{"create":false,"assign":false,"update":false,"resolve":false},"reports":{"view":false,"export":false}}');

-- Initial stays and rent plans derived from residents

INSERT OR REPLACE INTO stays (id, organization_id, resident_id, property_id, room_id, room_number, bed_id, bed_number, start_date, monthly_rent_at_start, status) VALUES ('stay-res-1', 'org-demo-pgwalo', 'res-1', 'prop-1', NULL, '204', 'prop-1-204-Bed B', 'Bed B', '2025-08-15', 9500, 'Current');
INSERT OR REPLACE INTO stays (id, organization_id, resident_id, property_id, room_id, room_number, bed_id, bed_number, start_date, monthly_rent_at_start, status) VALUES ('stay-res-2', 'org-demo-pgwalo', 'res-2', 'prop-1', NULL, '101', 'prop-1-101-Bed A', 'Bed A', '2025-06-01', 14500, 'Current');
INSERT OR REPLACE INTO stays (id, organization_id, resident_id, property_id, room_id, room_number, bed_id, bed_number, start_date, monthly_rent_at_start, status) VALUES ('stay-res-3', 'org-demo-pgwalo', 'res-3', 'prop-1', NULL, '204', 'prop-1-204-Bed A', 'Bed A', '2025-09-10', 9500, 'Current');
INSERT OR REPLACE INTO stays (id, organization_id, resident_id, property_id, room_id, room_number, bed_id, bed_number, start_date, monthly_rent_at_start, status) VALUES ('stay-res-4', 'org-demo-pgwalo', 'res-4', 'prop-1', NULL, '302', 'prop-1-302-Bed C', 'Bed C', '2026-01-10', 8500, 'Current');

INSERT OR REPLACE INTO rent_plans (id, organization_id, resident_id, property_id, monthly_rent, due_day, effective_from, status) VALUES ('rent-plan-res-1', 'org-demo-pgwalo', 'res-1', 'prop-1', 9500, 7, '2025-08-15', 'Active');
INSERT OR REPLACE INTO rent_plans (id, organization_id, resident_id, property_id, monthly_rent, due_day, effective_from, status) VALUES ('rent-plan-res-2', 'org-demo-pgwalo', 'res-2', 'prop-1', 14500, 7, '2025-06-01', 'Active');
INSERT OR REPLACE INTO rent_plans (id, organization_id, resident_id, property_id, monthly_rent, due_day, effective_from, status) VALUES ('rent-plan-res-3', 'org-demo-pgwalo', 'res-3', 'prop-1', 9500, 7, '2025-09-10', 'Active');
INSERT OR REPLACE INTO rent_plans (id, organization_id, resident_id, property_id, monthly_rent, due_day, effective_from, status) VALUES ('rent-plan-res-4', 'org-demo-pgwalo', 'res-4', 'prop-1', 8500, 7, '2026-01-10', 'Active');

